services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-for-custom-nodes
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data/database.sqlite:/home/node/.n8n/database.sqlite
      - ./n8n-data/config:/home/node/.n8n/config
      - ./n8n-data/binaryData:/home/node/.n8n/binaryData
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_LOG_LEVEL=info
      - DB_SQLITE_POOL_SIZE=2
      - N8N_RUNNERS_ENABLED=false
    restart: unless-stopped