services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-for-custom-nodes
    ports:
      - "5678:5678"
    volumes:
      - ./n8n-data:/home/node/.n8n/data
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_LOG_LEVEL=info
      - DB_SQLITE_POOL_SIZE=2
      - N8N_RUNNERS_ENABLED=false
      - N8N_USER_FOLDER=/home/node/.n8n/data
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
    restart: unless-stopped
